name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt || pip install pandas>=2.3.2 pyside6>=6.9.2
          pip install pyinstaller

      - name: Build bundle
        run: |
          pyinstaller --noconsole --onedir --name Chrono main.py

      - name: Zip dist folder
        run: |
          cd dist
          powershell -Command "Compress-Archive -Path 'Chrono' -DestinationPath 'Chrono.zip' -Force"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrono-zip
          path: dist/Chrono.zip
